#!/bin/bash

echo "🚀 VR DIGITAL INDIA - GO LIVE SCRIPT"
echo "===================================="
echo ""
echo "🌐 Your Live Website URL:"
echo "https://rajukumar-lab.github.io/VR-DIGIAL-INDIA/"
echo ""
echo "📋 To enable GitHub Pages:"
echo "1. Visit: https://github.com/RAJUKUMAR-LAB/VR-DIGIAL-INDIA/settings/pages"
echo "2. Source: Deploy from a branch"
echo "3. Branch: main"
echo "4. Folder: / (root)"
echo "5. Click Save"
echo ""
echo "⏱️  Wait 2-3 minutes for deployment"
echo "✅ Your website will be LIVE!"
echo ""
echo "📱 All Live Pages:"
echo "• Main: https://rajukumar-lab.github.io/VR-DIGIAL-INDIA/"
echo "• Dashboard: https://rajukumar-lab.github.io/VR-DIGIAL-INDIA/dashboard.html"
echo "• Status: https://rajukumar-lab.github.io/VR-DIGIAL-INDIA/status.html"
echo ""
echo "🎉 Ready for business 24/7!"